### ISSUE TITLE
Aspector does not work with prepended methods

### ISSUE THREAD

**Issue by mensfeld** [gcao/aspector#31]
``` ruby
require './lib/aspector'

module Mod
  def test
    super
  end
end

class ARClass
  def test
  end
end

ARClass.prepend Mod

class Hooks < Aspector::Base
  before :test do
  end
end

Hooks.apply(ARClass)

ar = ARClass.new
ar.test
```

```
aspector/interception.rb:302:in `call'
aspector/interception.rb:302:in `block in recreate_method_with_advices'
from test.rb:5:in `test'
aspector/interception.rb:302:in `call'
aspector/interception.rb:302:in `block in recreate_method_with_advices'
from test.rb:5:in `test'
aspector/interception.rb:302:in `call'
aspector/interception.rb:302:in `block in recreate_method_with_advices'
 ... 6271 levels...
aspector/interception.rb:302:in `call'
aspector/interception.rb:302:in `block in recreate_method_with_advices'
from test.rb:5:in `test'
from test.rb:25:in `<main>'
```

**Comment by mensfeld** [comment]
It happens only if aspect is added after module were prepended

**Comment by mensfeld** [comment]
Won't work. We've decided to deprecate this lib in favor of native ruby prepend.
